name: CI/CD for Job Application Prediction Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Job Application Prediction Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install jq (JSON Validator)
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Authenticate Service Account
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > /tmp/gcs-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcs-key.json

    - name: Configure GCP Project and Region
      run: |
        gcloud config set project smart-cove-444508-k0
        gcloud config set run/region us-central1

    - name: Enable Required Google Cloud APIs
      run: |
        gcloud services enable \
          artifactregistry.googleapis.com \
          run.googleapis.com \
          cloudresourcemanager.googleapis.com \
          iam.googleapis.com \
          storage.googleapis.com

    - name: Build Pipeline Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/smart-cove-444508-k0/job-app-repo/pipeline:${{ github.sha }} .

    - name: Push Pipeline Docker Image to Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker push us-central1-docker.pkg.dev/smart-cove-444508-k0/job-app-repo/pipeline:${{ github.sha }}

    - name: Deploy Pipeline to Google Cloud Run
      run: |
        gcloud run deploy job-app-pipeline \
          --image us-central1-docker.pkg.dev/smart-cove-444508-k0/job-app-repo/pipeline:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json \
          --service-account=397631499407-compute@developer.gserviceaccount.com

    - name: Build Gradio Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/smart-cove-444508-k0/job-app-repo/gradio:${{ github.sha }} .

    - name: Push Gradio Docker Image to Artifact Registry
      run: |
        docker push us-central1-docker.pkg.dev/smart-cove-444508-k0/job-app-repo/gradio:${{ github.sha }}

    - name: Deploy Gradio to Google Cloud Run
      run: |
        gcloud run deploy job-app-gradio \
          --image us-central1-docker.pkg.dev/smart-cove-444508-k0/job-app-repo/gradio:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json \
          --service-account=397631499407-compute@developer.gserviceaccount.com